### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by arianaa30** [Pratik08/Vis-DSS#2]
Hi,
Would you be adding some documentation of the algorithms? For instance, how does `SimpleVidSumm` work? What are some details behind using Color Histogram features?
Thanks.

**Comment by Pratik08** [comment]
Hello,
It's very unlikely that we would be adding any documentation to this repository in the near future. For more details on the implementation of the algorithms in the repository, you can refer our paper [here](https://arxiv.org/abs/1809.08846).

**Comment by arianaa30** [comment]
Thanks. Forgot about your paper.
With huge difficulties I compiled your code. The deepVidSumm still throws a segmentation fault for me :-/
